version: '3.2'

volumes:
  mysql-data:
  phpmyadmin-volume:

services:
  frontend:
    build: frontend
    ports:
      - 20080:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
      - ./config/apache/sites-available:/etc/apache2/sites-available
      - ./config/php/conf.d:/usr/local/etc/php/conf.d
    links:
      - data_base:db
    env_file:
      - .env

  data_base:
    image: mariadb:10.9.3
    environment:
      - MYSQL_ROOT_PASSWORD=252800nz
      - MYSQL_DATABASE=hrm_system
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=456654nz
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - '3306:3306'
  phpmyadmin:
    image: phpmyadmin:5.2.0
    volumes:
      - phpmyadmin-volume:/etc/phpmyadmin/config.usr.inc.php
    links:
      - data_base:db
    ports:
      - '82:80'
  netshoot:
    image: nicolaka/netshoot:latest
  selenium:
    image: selenium/standalone-firefox
    network_mode: "host"
    shm_size: "2g"
  #pgsql:
  #  image: postgres:9.5
  #  environment:
  #    - POSTGRES_DB=yii2advanced
  #    - POSTGRES_USER=yii2advanced
  #    - POSTGRES_PASSWORD=secret